### ISSUE TITLE
The Outer Worlds doesn't work

### ISSUE THREAD

**Issue by Kiffmet** [z0z0z/mf-install#53]
I cannot get this to work with The Outer Worlds. Gentoo x64. Does this require certain packages (maybe in 32bit also)? I've installed several different gstreamer plugins and my ffmpeg has support for every video codec. What can I do to make this work?

**Comment by z0z0z** [comment]
It's been years since I used Gentoo, but make sure you have USE flags set for building Wine with gstreamer support, including 32bit.

https://wiki.gentoo.org/wiki/Wine

This has some info.

I don't regret switch from Gentoo to Arch. I couldn't stand the chaos of running a non-binary distro and you can build your own custom packages just as easy on Arch anyway.

**Comment by Kiffmet** [comment]
OK I found the issue. Seems like mfplat can't handle more than 16 threads (I have a 3900X). By setting "System Options"->"Show Advanced Settings"->"Command Prefix"->"taskset -c 0-15" (without the quotation marks) in Lutris for the Epic Games Store it works flawlessly.

In Steam, setting the launch options to "taskset -c 0-15 %command%" also fixes "Remnant: From the Ashes" for me. Maybe you can include this workaround in README.md?

Btw, I switched to Gentoo after 3 happy years with Arch. At some point I just wanted a balls to the wall optimized system though :P

**Comment by z0z0z** [comment]
`Maybe you can include this workaround in README.md?`

This has already been in the README for weeks actually.

**Comment by Kiffmet** [comment]
Ahh yes, whoopsie.
