### ISSUE TITLE
I'm sorry for the stupid question, but how do I use this?

### ISSUE THREAD

**Issue by tunanachos** [z0z0z/mf-install#64]
Again, I'm sorry for such a silly question - the failing is on my interpretation and not the documentation.

I've downloaded it and extracted it but where should I place this? 

I've tried placing it in my `~/home/` folder but this doesn't work - do I add the extracted file to the games folders, if so, which and where? 

I'm very sorry again for a silly question. Thank-you.

**Comment by tunanachos** [comment]
I have tried unzipping it, `cd`ing to the directory and running `export WINEPREFIX="/steamapps/compatdata/961620/pfx` and `export PROTON="/steamapps/common/Proton 4.11" ./mf-install.sh -proton` to attempt to get Flashback working.

However when trying this I get the following error; 

![image](https://user-images.githubusercontent.com/40058681/81485290-de675700-9243-11ea-808f-a4ff691b5bea.png)


no doubt I'm doing something wrong, so if someone could clarify exactly how I use this I would be most grateful. Thanks again :-)

**Comment by AwesamLinux** [comment]
If this helps here is an example on how I use it

- Install winetricks ("sudo apt install winetricks" on Mint)
- Launch the game once on Steam (this so that the compatdata folder for the game is created)
- Run the mf-install script with this command:

WINEPREFIX="/mnt/Games/SteamLibrary/steamapps/compatdata/399810/pfx" /mnt/Games/mf-install-master/install-mf.sh

(I had downloaded and extracted mf-install files in /mnt/Games/mf-install-master/. And I have my Steam library installed at /mnt/Games/SteamLibrary/. 399810 is the Steam AppID of a game, 399810 in this case is Call of Cthulhu),

**Comment by z0z0z** [comment]
Where is your Steam library folder? By default it's in:

`$HOME/.local/share/Steam/steamapps`

So you said you want to install this for Flashback? The Steam app game ID is 961620

A folder called this should exist if you've ran it before:

`$HOME/.local/share/Steam/steamapps/compatdata/961620/pfx`

This is the Wine prefix that Steam has created for the game.

So download the mf-install script, open a terminal in the same folder as the script, and run

`WINEPREFIX="$HOME/.local/share/Steam/steamapps/compatdata/961620/pfx" ./mf-install.sh`

**Comment by tunanachos** [comment]
Hello & thank-you to you both _(especially @z0z0z once again I'm sorry for such a silly question)_

My `steam` folder is installed on a different HDD _(my path was `/run/media/tuna/steam/steamapps/`)_


After navigating to the correct path for my game I typed out;

`WINEPREFIX="/run/media/tuna/steam/steamapps/compatdata/961620/pfx" ./mf-install.sh`

and it worked - I'm happy to say Flashback is now working :-) 

solved! & Thanks again for both of your time - you've my total gratitude
